### Array Programming with Numpy 

Numpy is open source numeric and scientific computations library created around 2005. It combines the best of the previous two libraries Numeric package(created in mid-90s) and Numarray. It has now become widely popular for manipulating, cleaning and munging data. Numpy is also highly popular in scientific community and has recently been used to perform computations needed to discover black holes and gravitational waves.  It provides a multidimensional Python array object (a data structure that efficiently stores and accesses tensors) along with array-aware functions that operate on it. 

I wrote a blog post associated with it: https://asjadkhan.ghost.io/ghost/#/editor/post/5f62b4b8672f7e00394a960f

A lot of code has been inspired from following resources: 

- https://cs231n.github.io/python-numpy-tutorial/
- https://jakevdp.github.io/PythonDataScienceHandbook/
- Python-for-Data-Analysis-2nd-Edition
- Array programming with NumPy

In [8]:
import numpy as np

### Creating an array from python list

We can create a numpy array using a number for methods. For example we can pass any sequence like python list to create a 1-dimensional array or nested lists to create mulit-dimensional lists.  


In [9]:
my_data = [6, 7.5, 8, 0, 1]

we use the array function which accepts any sequence like objects

In [10]:
my_np_array = np.array(my_data)

### creating a multi-dimensional array by passing nested lists

In [11]:
my_mdata = [[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]]
my_marray = np.array(my_mdata) # This creates a 3x3 matrix with entries having int datatype. 
my_marray 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
my_marray.shape,  my_marray.dtype

((3, 4), dtype('int64'))

what happens when we create a numpy array? 

![alt text](numpy.png "Logo Title Text 1")

The data Structure contains consists of a pointer to memory, along with metadata used to 
interpret the data stored there, notably ‘data type’, ‘shape’ and ‘strides’


### Creating Arrays from Scratch




In [16]:
#N-dimensional array object, or ndarray

#Let's create a 5x5 array with random entries having type float64.

data = np.random.randn(5, 5)

In [17]:
data

array([[-0.06280083, -0.81163055,  1.49506972, -1.39209472, -0.01189743],
       [-0.19564221,  2.13715337,  0.41425139,  0.55194035, -0.71816686],
       [ 1.9093237 ,  0.23959842, -1.15354414,  1.52940897, -0.82104251],
       [-1.45079794, -0.75344316,  0.68589017, -0.28548721, -1.36159532],
       [ 0.43797451, -0.02953956,  0.20648365, -1.077761  ,  0.00252675]])

#### We can also check their type 

In [18]:
data.shape, data.dtype

((5, 5), dtype('float64'))

Numpy supports real and complex numbers (of lower and higher precision), strings, timestamps and pointers to Python objects and we can access elements using the index. The shape of an array determines the number of elements along each axis, and the number of axes is the dimensionality of the array. The data type describes the nature of elements stored in an array. An array has a single data type, and each element of an array occupies the same number of bytes in memory. Examples of data types include real and complex numbers (of lower and higher precision), strings, timestamps and pointers to Python objects[2]. 

### Identity Matrix

In [35]:
identity_matrix = np.identity(10, dtype = int)

In [36]:
identity_matrix.shape, identity_matrix.dtype

((10, 10), dtype('int64'))

In [37]:
identity_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## Indexing and Slicing

We can interact with NumPy arrays using ‘indexing’. Array indexing is a rich topic its best. The general syntax is as follows: 

```
X[start:end:step] #any of which can be left blank

```

These operations return a ‘view’ of the original data. To learn about it by trying some code:  

In [41]:
my_np_array[1:2]  #1-D array can be sliced same as 

array([7.5])

In [43]:
my_np_array[3:5] = 0
my_np_array

array([6. , 7.5, 8. , 0. , 0. ])

In [47]:
my_np_array[:] = 99

In [48]:
my_np_array

array([99., 99., 99., 99., 99.])

#### Multi-dimensional Arrays 

In [80]:
#new array

my_mdata = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])

In [68]:
my_mdata[:2] #select the first two rows of the multi-dimensional array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
my_mdata[:2,1:] #select first two rows and columns 1 onwards 

array([[2, 3, 4],
       [6, 7, 8]])

In [71]:
my_mdata[2,:]  #select third row

array([ 9, 10, 11, 12])

In [72]:
my_mdata[2] #select third row

array([ 9, 10, 11, 12])

In [73]:
my_mdata[2:,:] #select row third onwards and all columns

array([[ 9, 10, 11, 12]])

In [75]:
my_mdata[:,2] #all rows of third column

array([ 3,  7, 11])

In [76]:
my_mdata[:,:2] #all rows of first two columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [79]:
my_mdata[1,:2] #second row and elements of first two columns

array([5, 6])

In [77]:
my_mdata[1:2, :2]

array([[5, 6]])

In [81]:
my_mdata

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
![alt text](slicing.png "Logo Title Text 1")
